### ISSUE TITLE
Review: unify calendar validity checks

### ISSUE THREAD

**Issue by ryzokuken** [tc39/intl-displaynames-v2#25]
You have added a calendar validity check in https://github.com/tc39/intl-displaynames-v2/blob/2b098325b9cba1f922b7e3a83f1a3557d37ffd59/displaynames.html#L28. There is an existing validity check in ECMA-402 at https://github.com/tc39/ecma402/blob/master/spec/locale.html#L121, which doesn't exactly match.

You should atleast change the new one to match the other and perhaps better, refactor the check into a simple abstract operation, perhaps called `IsValidCalendar`. One thing to note is that Temporal goes a step further and defines the grammar. Perhaps we should reference that so that worst case we're referring to an ECMA document and best case we'd be referring to something from ECMA-262 (soon hopefully). 

I can understand if you want to wait until Temporal is Stage 4, but perhaps we should atleast unify the calls in a single AO so it can be easily done later.

**Comment by FrankYFTang** [comment]
ok, I think that came from inconsistence within the current ECMA402

https://tc39.es/ecma402/#sec-initializedatetimeformat
7.a. If calendar does not match the Unicode Locale Identifier type nonterminal, throw a RangeError exception.

https://tc39.es/ecma402/#sec-Intl.Locale
7.a. If calendar does not match the type sequence (from UTS 35 Unicode Locale Identifier, section 3.2), throw a RangeError exception.

Currently in this proposal https://tc39.es/intl-displaynames-v2/#sec-canonicalcodefordisplaynames
 it is 
4.a If code does not match the Unicode Locale Identifier type nonterminal, throw a RangeError exception.
which match https://tc39.es/ecma402/#sec-initializedatetimeformat instead of https://tc39.es/ecma402/#sec-Intl.Locale

so I think the issue is really the current ECMA402 in the Locale section those option validation are differ from other older spec text.

**Comment by ryzokuken** [comment]
I think all three calls should move to a single callsite, perhaps just move the best (IMO from `Intl.Locale`) to a new abstract operation and call it from all three.

**Comment by FrankYFTang** [comment]
Filed https://github.com/tc39/ecma402/issues/565 and depend on which way we change the text to resolve the other part of ECMA402 text, I could then adjust the proposal to match that, otherwise, I will just switch from inconsistent one to be inconsistent with another.

**Comment by FrankYFTang** [comment]
> at least change the new one to match the other 
It is now matched. Close the bug.
